### ISSUE TITLE
Instruction Mistake

### ISSUE THREAD

**Issue by andrewthad** [pbrisbin/vim-syntax-shakespeare#22]
On the readme, the instruction reading
Add `Plugin "pbrisbin/vim-syntax-shakespeare"`
needs to have single quotes instead:
Add `Plugin 'pbrisbin/vim-syntax-shakespeare'`
Vim treats double quotes as a comment.

**Comment by pbrisbin** [comment]
> Vim treats double quotes as a comment.

Are you sure? I thought was smart enough to know when you delimit a string.

`:echo "foo"` works fine in my vim.

I'll probably change it to avoid confusion, but I'm curious if it's a real problem.

**Comment by andrewthad** [comment]
Sorry. I guess I meant that it doesn't work when I put it in my `.vimrc` file and that I have to use single quotes there.

**Comment by pbrisbin** [comment]
Oh yeah, I knew what you meant. I thought the `:echo` was a valid test, assuming that if vim handled it correctly there, it'd handle it in the `Plugin` case to. I also changed my `~/.vimrc` to use double quotes and re-`:source`d it from within vim without error. Turns out, even though both of these cases work fine, leaving my `~/.vimrc` with double quotes and actually exiting/relaunching did produce the errors.

Long way of saying: nice catch, thanks.
